# fly.toml app configuration file generated for fb-ai-bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'fb-ai-bot'
primary_region = 'arn'

[build]

[deploy]
  # Stop old machine before starting new one (avoids volume lock)
  strategy = "immediate"

[env]
  DATABASE_URL = "file:/data/dev.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data"
  destination = "/data"

[env]
  DATABASE_URL = "postgresql://<user>:<password>@<host>:5432/<database>?schema=public"
